---
- hosts: azure
  sudo: yes
  remote_user: backendsi2
  tasks:
    - name: Descargar/Actualizar repo.
    git: repo=https://github.com/iblancasa/BackendSI2-IV.git dest=/home/backendsi2/BackendSI2-IV accept_hostkey=yes
    notify: Reiniciar
    handlers:
      - include: handlers.yml